
# Dossier contenant les installeur.
# Dois etre organiser comme suit :  [Premiere Lettre]/[Nom du jeu]/
# exemple : A/Alan Wake/
# Les .exe sont conciderer comme un installer
folder.instalers=/media/Medias/GOG/
folder.games=~/Games/
folder.proton=~/Games/.proton/
folder.datas=~/Games/.datas/
folder.steam=~/.steam/steam/
